.all: main.c
	gcc main.c -o main
	./main tests/input1 tests/output1

.tests: main.c
	./main tests/input1 tests/output1
	./main tests/input2 tests/output2
	./main tests/input3 tests/output3
	./main tests/input4 tests/output4
	./main tests/input5 tests/output5
